# Updated with Current settings.
language: node_js
node_js:
  - 13

branches:
  only:
  - master
  - staging

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t 05-api-feed .
  - docker tag 05-api-feed gonzaga626/05-api-feed:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push gonzaga626/05-api-feed