apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-feed-svc
  name: api-feed-svc
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: api-feed-svc
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
